---
title: "YOUR-NAME'S Lab Notebook"
format: html
---
# Using the lab notebook

The goal for this repository/notebook is to serve as a template that you can modify to establish your very own digital lab notebook!
Click around on the tabs above to explore some of the functionality of this template site.

This notebook is yours and is to track the work you do in the Introduction to Bioinformatics Lab (Fall - 2026).
It is critical that this stays up to date, as it acts as the predominant means to track lab work for grading.

To keep your notebook up-to-date, you will be relying on GitHub, which is an amazing repository for handling
diverse bioinformatic tasks, including the maintenance of your notebook as a website (woo!). Building familiarity
with Git is one of the most important tasks in learning bioinformatics.

Below is how to set up your notebook initially!

# Setting up your notebook
:::{.callout-note collapse="true"}
### Preparing R GUI for Your Notebook
Before the rendering of your notebook will work, we need to install R and R-Studio.

1) From your preferred browser, download and install [R](https://www.r-project.org/)
2) Afterwards install [R-Studio](https://posit.co/downloads)

Then you are set!
:::

:::{.callout-note collapse="true"}
### Installing Quarto Through the CLI with Pixi

While the R-Studio approach works well, especially as we will use R in this lab,
if you are interested in managing your notebook solely through the command-line,
you can follow the steps below. If you choose this approach, I recommend using
[Pixi](https://pixi.prefix.dev/latest/#installation), a workspace manager (like
containers), to install and manage the necessary software. This works,
but is a less intuitive experience and I do not totally recommend it.

1) Open up your terminal (or git-bash)

2) Follow the installation information for Pixi for your computer [pixi installation](https://pixi.prefix.dev/latest/installation/#__tabbed_1_1)

3) On your Desktop, make a new folder called `Pixi_Envs`

4) In your terminal, move to the newly created folder

5) Make another new folder called `quarto`, then move inside there too!

6) create our `quarto` workspace and install the necessary tools
   ```bash
   pixi init
   pixi add quarto r
   ```

7) you may be asked to pick a mirror to install R. If so, just type `63` and hit `enter`

8) Go ahead and "register" the workspace
   ```bash
   pixi workspace register
   ```

9) Now you can activate this workspace from anywhere on your computer! Below is the code to do so:
   ```bash
   pixi shell -w quarto
   ```
:::

# Verifying that the notebook builds on your system

Before moving on, let's verify that the lab notebook can render properly on your local system.

:::{.callout-note collapse="true"}
#### RStudio Rendering
1) Load up R-RStudio

2) Open the `labnotebook.Rproj` in your lab notebook folder as an R-project (with R-studio)

3) IF you have note already installed the `rmarkdown` package with R, let's do that now. Otherwse, skip this step!
   ```r
   install.packages('rmarkdown')
   ```

4) Load the 'rmarkdown' package
   ```r
   library('rmarkdown')
   ```

5) Once ready, all you have to do is render your notebook (i.e. make the website!).
There are two ways to do this:
   - In the upper right R-Studio pane, is the `Build` tab. Click on this, then the `Render Website` button!
   - All you have to do is type `ctl`+`shift`+`b`
:::

:::{.callout-note collapse="true"}
#### Command-line Rendering
1) Make sure that you have used the terminal commands to move into your lab notebook folder

2) Ensure that your quarto workspace is active. If it is not, run the following command:
   ```bash
   pixi shell -w quarto
   ```

3) Render your HTML files
   ```bash
   quarto render
   ```

4) Your updated files will be found in the `_site` folder. Go ahead and open the `index.html` file, which will show you what your notebook updates will look like.
:::

Enjoy looking at the local version of your notebook! The steps to interact with GitHub to publish your
notebook, can be found in the `Guided Labs` tab of your notebook.
