---
title: "Working with SRA Data"
author: "YOUR-NAME"
date: 2026-09-09
projects: "guided-learning"
keywords:
  - sra
  - fastq
  - trimming
  - downloading
  - hpc
---

# Goals of the lab overall

The skills acquired in this lab class are crucial for bioinformatic tasks using molecular data, such as data analysis, scripting,
and working in high-performance computing (HPC) environments. My hope is that you don’t just type the commands into the terminal and
move on -- I would like you to ***think*** about what these commands are doing and start imagining how they could be useful in analyzing your own data.

## For your success in the lab
Each lab is inteded to be a reference point for you on various bioinformatic tasks.
To make the most of these labs, please treat them like a **personal resource**, so
adjust any specific commands accordingly.

---

# Lab Deep-dive

---

### Overview of today's lab
Today's lab will include downloading and manipulating raw sequencing data stored in NCBI's
short read archive.

This is the first step to many downstream analyses. While not always required, it is a
crucial and common step for numerous bioinformatics analyses. While the individual steps
do not take much time to perform, it is crucial to build your familiarity with job submission
scripts and moving data from local to remote hosts (i.e., your laptop to/from the HPC).

Make sure to ask questions as needed!

### Downloading, inspecting, and trimming SRA datasets
- [ ] Logging on to the HPC!
- [ ] Making a job submission script
- [ ] Downloading SRA datasets
- [ ] Running QC analyses
- [ ] Trimming the reads
- [ ] Checking the QC of the trimmed reads!

## Before we get started
Today, we will be using previously published data from Zhao **et al.** (2015). On
Blackboard you will see a PDF of the paper, as well as the `DGE.Drosophila.Metadata.csv`
file. You will need the information in this file, which includes all the relevant
metadata associated with the experiment. While you will rely on this file today to
download the raw sequencing data (`SRR numbers`), you will be updating this file
in the next `qmd` file, as this lab/page is focused **solely** on the initial
data downloading and processing.


## Connecting to `bora.sciclone.wm.edu` and preparing for today's lab

We are going to first access the HPC again, as you did in our first lab. Refer to
your notes as needed!

1. Download your empty lab reposity from GitHub (only need to do this the first day)
   ```bash
   ssh wm-username@bora.sciclone.wm.edu
   ```

2. Move into your lab folder (this should be in the `scr10` directory)
   ```bash
   YOUR CODE HERE
   ```

3. Make a new directory called `raw_read_prep` if you have not already!

   ::: {.callout-tip title="In case you get stumped" collapse="true"}
   Use the `mkdir` command to make a new directory!
   ```bash
   mkdir raw_read_prep
   ```
   :::

4. Move into your new `raw_read_prep` folder

   ::: {.callout-tip title="In case you get stumped" collapse="true"}
   Use the `cd` command to move into your new directory!
   ```bash
   cd raw_read_prep
   ```
   :::

5. Load miniforge3 to get access to `conda`

   ::: {.callout-tip title="In case you get stumped" collapse="true"}
   ```bash
   module load miniforge3/24.9.2-0
   ```
   :::

6. Activate your `sra_prep` container

   ::: {.callout-tip title="In case you get stumped" collapse="true"}
   ```bash
   conda activate sra_prep
   ```
   :::

Great! Hopefully the navigation is getting easier!

---

## Downloading SRA datasets

You will need to make a copy of your job submission script that you created
during last week's lab, which you can then edit to make it easy to download and
process your raw read downloads!

1. Make sure you are in the `raw_read_prep` folder

   ::: {.callout-tip title="In case you get stumped" collapse="true"}
   Use the `cd` command to move into your new directory!
   ```bash
   cd raw_read_prep
   ```
   :::

2. Make a copy of last week's slurm script and rename it `sra_download.sh`
   ```bash
   cp ../Slurm_Scripts/prep_conda_env.sh ../Slurm_Scripts/sra_download.sh
   ```

   Did you notice that the above command uses **relative** paths to copy (`cp`) the file!

3. You need to edit the contents of the new `sra_download.sh` file! Use `nano` to
start editing the file

   ::: {.callout-tip title="In case you get stumped" collapse="true"}
   ```bash
   nano ../Slurm_Scripts/sra_download.sh
   ```
   :::

4. We will start by making a `for loop` using `bash` to download three of the
sequencing runs. You will be using `prefetch` to download the data. `prefetch` is
part of the `sratools` suite of tools that NCBI has released to make it easier to
access raw sequencing data from the `SRA` repository.

   Make sure to delete the existing command inside the file. Then add the following
   `for loop`.
   ```bash
   for seqrun in SRR1576457 SRR1576458 SRR1576459
   do
    prefetch -v $seqrun
   done
   ```

   Make sure to update the job-name! And this may take a little bit of time, so do not be alarmed!

5. Submit your job!

   ::: {.callout-tip title="In case you get stumped" collapse="true"}
   ```bash
   sbatch ../Slurm_Scripts/sra_download.sh
   ```
   :::

6. Check that your submitted batch job is running
   ```bash
   squeue --m
   ```

7. You can also check to see how many of the sequencing runs are downloaded/downloading
using the `ls` command. `prefetch` downloads the files into their own folders!

8. While there are ***nine*** more files to download, they will be up to you to
do on your own during the lab today. So feel free to reference this section as needed.

   You will need to make sure to edit the script, and update the sequencing run numbers.

   If you want, you can make edits to your job submission script, submit it using `sbatch`,
   and repeat! As soon as the job is submitted the contents of your job submission
   script are "remembered" by the head-node, so you are free to add more jobs to the queue!


## Unpacking SRA datasets
If you were curious and used `ls` to peek into those newly created folders, you
would have seen a file ending in `.sra`. This is the packed (compressed) raw data!

We need to unpack it using the tool `parallel-fastq-dump`.

Below, is a walkthrough of one way to do this. It is a bit involved, but it will
make it easy to link the file to the existing metadata!

*You should repeat the following steps for each file*

1. Make a copy of last week's slurm script and rename it `sra_fastq_dump.sh`
   ```bash
   cp ../Slurm_Scripts/prep_conda_env.sh ../Slurm_Scripts/sra_fastq_dump.sh
   ```

2. Make some extra edits to this file!
   - [ ] update the `job-name`
   - [ ] update the `--ntasks` value to `8`
   - [ ] delete the old command

3. Now we will add the command to run `parallel-fastq-dump`
   ```bash
   parallel-fastq-dump --split-files \
        --gzip \
        --threads 8 \
        -s SRR1576457 \
        -O Dmel_Maine_21C_Rep1
   ```

   Here is a breakdown of the command:
   - `--split-files`: separate the file into `forward` and `reverse` reads (the data are paired-end!)
   - `--gzip`: these raw `fastq` files can be big, so we will keep them compressed
   - `--threads 8`: tells the HPC to multi-task on this job, splitting the job into 8 pieces to speed it up
   - `-s SRR#`: tells the tool which dataset we want to process
   - `-O NAME`: the name we want the output folder to be. It is typically nice to include the metadata and/or the `SRR accession` (or both)

4. Using `sbatch`, submit the job!

5. Repeat for the other datasets that have ***FINISHED*** downloading.
Use `squeue --m` to check that the files you are trying to unpack have finished downloading!

6. As before, it is up to you to unpack the rest of the datasets during our time
in lab (or outside if that's easier). So long as one of the sequencing runs is
downloaded and unpacked, you can move on to the last section, which is trimming
and the quality checking!

## Trimming raw SRA datasets
If you were curious and used `ls` to peek into those newly created folders, you
would have seen a file ending in `.sra`. This is the packed (compressed) raw data!

We need to unpack it using the tool `parallel-fastq-dump`.

Below, is a walkthrough of one way to do this. It is a bit involved, but it will
make it easy to link the file to the existing metadata!

*You should repeat the following steps for each file*

1. Make a copy of the `sra_fastq_dump.sh` slurm script and rename it `fastq_trim.sh`

   ::: {.callout-tip title="In case you get stumped" collapse="true"}
   ```bash
   cp ../Slurm_Scripts/prep_conda_env.sh ../Slurm_Scripts/sra_fastq_trim.sh
   ```
   :::

2. You will need to edit the newly copied script, `sra_fastq_trim.sh`. As the prior
script already was set up for multi-threading (`--ntasks=8`), the only change is to
replace the prior command with one for our read-trimming tool, `fastp`.

   The command is below, followed by a breakdown of the options. The below command
   is written for just ***one*** file, so you will need to adjust this!

   ```bash
   fastp \
        -i Dmel_Maine_21C_Rep1/SRR1576457_1.fastq.gz \
        -I Dmel_Maine_21C_Rep1/SRR1576457_2.fastq.gz \
        -o Dmel_Maine_21C_Rep1.Fwd.20q.80nt.fastq.gz \
        -O Dmel_Maine_21C_Rep1.Rev.20q.80nt.fastq.gz \
        -h Dmel_Maine_21C_Rep1.html \
        -R "Dmel_Maine_21C_Rep1 Report" \
        -q 20  \
        -l 80 \
        -w 8 \
        -r
   ```

   Here is a breakdown of the command:
   - `-i`: PATH to your `forward` reads
   - `-I`: PATH to your `reverse` reads
   - `-o`: what to name your trimmed `forward` reads
   - `-O`: what to name your trimmed `reverse` reads
   - `-h`: what to name the output quality score `html` file
   - `-R`: the report name to add to the output quality score `html` file
   - `-q`: minimum Phred quality score to use for read trimming
   - `-l`: minimum read length to keep a read following trimming
   - `-w`: number of threads to use (this should ideally be the same as `--ntasks`)
   - `-r`: perform the per-base trimming starting on the right side of the read



4. Using `sbatch`, submit the job!

5. Repeat for the other datasets that have ***FINISHED*** unpacking with `parallel-fastq-dump`.
Use `squeue --m` to check that the files you are trying to unpack have finished downloading!

## Cleaning up after ourselves
By now, you will have tons of files, all sitting inside your `raw_read_prep` folder.
We do need to make sure to clean-up after ourselves on the HPC, as we have many
"intermediate" files, which take up a reasonably large amount of space.

To do our cleanup, we will be using a *dangerous* command, `rm`. What makes this
command so dangerous is that it removes the files/folders permanently. This is like
moving a file to your trash on your computer and tossing the trash out at the same
time.

Take your time when doing this! We will remove files little bit by little bit.

1. Running and submitting jobs to SLURM will generate a ton of "slurm.out" files.
These are logs from the HPC and the tool(s) you used. Typically, you won't need
these for very long, outside of handling errors.

   We can remove all of these in one step!

   ::: {.callout-warning title="Removing slurm logs"}
   ```bash
   rm slurm-*.out
   ```
   :::

   `rm` followed by a file, will remove the file. You can also use the `wildcard`
   character, `*`. In the example above, the way this is put in the command effectively
   tells the computer "remove anything that startswith `slurm-` ***and*** ends with `.out`"

2. Make sure to remove all the files that end with `.json` as we do not need these!

   ::: {.callout-warning title="Removing slurm logs"}
   ```bash
   rm *.json
   ```
   :::

3. This step is for any sequencing runs that have been **fully** processed, which includes downloading,
unpacking, trimming. We will start by removing each of the intermediate folders,
one at a time. It is okay to do this slowly and carefully, as you don't want to need
to do the processing over again.

   Below is the command to remove just one of the folders from the initial SRR downloading

   ::: {.callout-warning title="Removing Folders"}
   ```bash
   rm -rf SRR1576457
   ```
   :::

   You *can* combine this with the `wildcard` to remove all of the SRR folders,
   but you need to be very certain you have "unpacked" them!

   You can also use that command to remove *any* folders, but again, please be cautious!


## Downloading files to your local computer!
The read trimming tool, `fastp`, automatically generates quality score reports for you
to peruse! The only trouble is that these are stored on the HPC and you will need
to download them to your computer to view.

In a new terminal window, move to your Desktop. If you want, you can make a folder
specifically for these files, since the aim here is to really just look at them once.

I would not store them in the lab folder that is `pushed` to GitHub, but you are
free to make a new folder and store them there!

Once you are on your computer where you would like to download the files to, feel
free to run the following steps.

1. In the terminal that is logged onto the HPC, use `pwd` to get the `PATH` (location)
of where you currently are. This should be where the `.html` files are stored.
   ```bash
   pwd
   ```

   Copy the output location! You will paste it in the next command!

   Download ***all*** the `.html` to your current working directory on your
laptop.

   ```bash
   scp wm-username@bora.sciclone.wm.edu:PASTE-YOUR-PATH
   ```

---

# Quick Start Guide

---

This is for your reference in the future, so you don't have to slog through all the work above!
Also, what a great way to practice this week :)

Below, the steps are numbered with emtpy code blocks below them. Copy-paste your commands there!

1. Use `ssh` to log onto `bora`
   ```bash
   CODE GOES HERE
   ```

2. Move into your `raw_read_prep` directory inside your Biol404L directory
   ```bash
   CODE GOES HERE
   ```

3. Activate your conda `sra_prep` container (make sure to load miniforge3 first)
   ```bash
   CODE GOES HERE
   ```

4. Edit your `sra_download.sh` script to add, change, remove SRA accession numbers
to download
   ```bash
   CODE GOES HERE
   ```

5. Run your `sra_download.sh` script
   ```bash
   CODE GOES HERE
   ```

6. Edit your `sra_fastq_dump.sh` script to change the SRA accession numbers to unpack
and the output folder to store them.
   ```bash
   CODE GOES HERE
   ```

7. Run your `sra_fastq_dump.sh` script
   ```bash
   CODE GOES HERE
   ```

8. Edit your `fastq_trim.sh` script to change the compressed fastq files to trim
and the output names to save them.
   ```bash
   CODE GOES HERE
   ```

9. Run your `fastq_trim.sh` script
   ```bash
   CODE GOES HERE
   ```

10. Remember your cleaning commands!
    ```bash
    CODE GOES HERE
    ```

Make a small reference guide of steps for yourself down here!
